jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Kiểm tra thư mục
        run: ls -la

      - name: Cài đặt dependencies và build
        working-directory: ./  # Đảm bảo chạy lệnh đúng thư mục
        run: npm install && npm run build

